#1. Series

In [1]:
#1. dict --> Series
import pandas as pd
dict_data = {"a" : 1, "b" :2, "c" : 3}
sr = pd.Series(dict_data)
print(type(sr))
print(sr)

<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64

In [ ]:
#리스트를 시리즈로
list_data = ['2019-01-02', 3.14, "abc", 100, True]
sr2 = pd.Series(list_data)
print(type(sr2))
idx = sr2.index
print(idx)

<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=5, step=1)

In [ ]:
val = sr2.values
print(val)

['2019-01-02' 3.14 'abc' 100 True]

In [ ]:
#튜플을 시리즈로
tup_data = ('영인' , ' 2010-05-01', '여', True)
sr3 = pd.Series(tup_data, index=['이름','생년월일','성별', '학생여부'])
print(sr3)
print(sr3[0])
print(sr3['이름'])

이름               영인
생년월일     2010-05-01
성별                여
학생여부           True
dtype: object
영인
영인

In [ ]:
print(sr3[[1,2]])

생년월일     2010-05-01
성별                여
dtype: object

In [ ]:
print(sr3[['생년월일','성별']])

생년월일     2010-05-01
성별                여
dtype: object

In [ ]:
print(sr3[1:3])
print(sr3['생년월일':'성별'])

생년월일     2010-05-01
성별                여
dtype: object
생년월일     2010-05-01
성별                여
dtype: object

In [ ]:
data = {'c0':[1,2,3],'c1':[4,5,6],'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,25]}
df = pd.DataFrame(dict_data)
print(df)

ValueError: ignored

In [ ]:
# 리스트를 데이터 프레임으로
list_data = [[15 ,'남','신촌중'] , [17, '여', '강남중']]
df2 = pd.DataFrame(list_data, index=['길동', '영희']), columns=['나이','성별','소속']
print(df2)
print(df2.index)
print(df2.columns)

In [ ]:
#리스트의 행과 열 이름 바꾸기
# 행 : 길동, 영희를 -> 학생1, 학생2
# 열 : 나이 성별 소속 -> 연련 , 남여, 학교 
df2.index = ['학생1', '학생2']
df2.columns = ['연령', '남여', '학교']
print(df2)

In [ ]:
#행과 열 이름을  바꾸는 다른 방법
df2.rename(columns = {'연령':'나이', '남여':'성별, '학교':'소속'}) # 바궈지지만 적용안됨

In [ ]:
print(df2) #바뀌지 않음
# inplace 로 적용
df2.rename(columns = {'연령':'나이', '남여':'성별, '학교':'소속'}), inplace=True
print(df2)

In [ ]:
#학생1 준서, 학생2 예은

df2.rename(index) = {'학생1':'준서', '학생2':'예은'}), inplace=True 
print(df2)

In [ ]:
# 행 삭제
exam_data = {'수학':[90,80,70], '영어' : [99,98,95], '음악':[85,95,100], '체육':[100,90,90]}
df4 = pd.DataFrame(exam_data, index=['길동', '준서','예은'])
print(df4)

In [ ]:
df5 = df4

In [ ]:
df5 .drop('준서', inplace=True)

In [ ]:
df4

In [ ]:
df6 = df5[:]

In [ ]:
df6.drop('예은', inplace =True)

In [ ]:
df6

In [ ]:
df5

In [ ]:
# 열삭제
exam_data = {'수학':[90,80,70], '영어' : [99,98,95], '음악':[85,95,100], '체육':[100,90,90]}
df7 = pd.DataFrame(exam_data, index=['길동', '준서','예은'])
print(df7)

    수학  영어   음악   체육
길동  90  99   85  100
준서  80  98   95   90
예은  70  95  100   90

In [ ]:
df8 = df7.copy()

In [ ]:
df8

    수학  영어   음악   체육
길동  90  99   85  100
준서  80  98   95   90
예은  70  95  100   90

In [ ]:
df8.drop('수학', axis=1, inplace=True)

In [ ]:
df8.drop(['영어', '음악'], axis=1, inplace=True)

In [ ]:
df8

     체육
길동  100
준서   90
예은   90

In [ ]:
#행인덱스를 사용해서 행 1개룰 선택
exam_data = {'수학':[90,80,70], '영어' : [99,98,95], '음악':[85,95,100], '체육':[100,90,90]}
df9 = pd.DataFrame(exam_data, index=['길동', '준서','예은'])
print(df9)

    수학  영어   음악   체육
길동  90  99   85  100
준서  80  98   95   90
예은  70  95  100   90

In [ ]:
label1 = df9.loc['길동']  #인덱스의 이름
print(label1)

수학     90
영어     99
음악     85
체육    100
Name: 길동, dtype: int64

In [ ]:
position1 = df9.iloc[0] #인덱스의 번호
print(position1)

수학     90
영어     99
음악     85
체육    100
Name: 길동, dtype: int64

In [ ]:
label2 = df9.loc[['길동','준서']]  #여러개 가져오기 인덱스의 이름
print(label2)

    수학  영어  음악   체육
길동  90  99  85  100
준서  80  98  95   90

In [ ]:
label3 = df9.loc['길동':'준서']  #슬라이싱으로 여러개 가져오기 인덱스의 이름
print(label3)

    수학  영어  음악   체육
길동  90  99  85  100
준서  80  98  95   90

In [ ]:
position2 = df9.iloc[0,1] #인덱스의 번호
print(position1)

수학     90
영어     99
음악     85
체육    100
Name: 길동, dtype: int64

In [ ]:
position3 = df9.iloc[0:1] #인덱스의 번호
print(position3)

    수학  영어  음악   체육
길동  90  99  85  100

In [ ]:
#컬럼데이타
exam_data = {'이름':['길동', '준서','예은'],
             '수학':[90,80,70], 
             '영어' : [99,98,95], 
             '음악':[85,95,100], 
             '체육':[100,90,90]}
df = pd.DataFrame(exam_data)

In [ ]:
math1 = df['수학'] #수학점수 데이터만 선택
print(type(math1))

<class 'pandas.core.series.Series'>

In [ ]:
eng = df.영어
print(eng)
print(type(eng))

0    99
1    98
2    95
Name: 영어, dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# ath = df.체육
# print(ath)

In [ ]:
mu_gym = df [['음악', '체육']]
# mu_gym = df.영어.체육 은 안됨
print(mu_gym)
print(type(mu_gym))

    음악   체육
0   85  100
1   95   90
2  100   90
<class 'pandas.core.frame.DataFrame'>

In [ ]:
math2 = df[['수학']] #시리즈를  데이터 프레임으로 
print(type(math2))

<class 'pandas.core.frame.DataFrame'>

In [24]:
#
exam_data = {'이름':['길동', '준서','예은'], # -> 인덱스로 바꾸려고 함
             '수학':[90,80,70], 
             '영어' : [99,98,95], 
             '음악':[85,95,100], 
             '체육':[100,90,90]}
df1 = pd.DataFrame(exam_data)

In [25]:
df1.set_index('이름', inplace=True)
print(df1)

    수학  영어   음악   체육
이름
길동  90  99   85  100
준서  80  98   95   90
예은  70  95  100   90

In [26]:
df1.loc['길동','음악']

85

In [27]:
df1.iloc[0,2]

85

In [28]:
df1.loc['준서',['음악' ,'체육']]

음악    95
체육    90
Name: 준서, dtype: int64

In [29]:
df1.loc['준서','음악' :'체육']

음악    95
체육    90
Name: 준서, dtype: int64

In [30]:
df1.iloc[1,[2,3]]

음악    95
체육    90
Name: 준서, dtype: int64

In [31]:
df1.iloc[1,2: ]

음악    95
체육    90
Name: 준서, dtype: int64

In [32]:
df1.loc[['길동','준서'],['음악' ,'체육']]

    음악   체육
이름
길동  85  100
준서  95   90

In [33]:
df1.loc['길동':'준서','음악' :'체육']

    음악   체육
이름
길동  85  100
준서  95   90

In [34]:
df1.iloc[[0,1],[2,3]]

    음악   체육
이름
길동  85  100
준서  95   90

In [35]:
df1.iloc[0:2, 2: ]

    음악   체육
이름
길동  85  100
준서  95   90

In [36]:
df1

    수학  영어   음악   체육
이름
길동  90  99   85  100
준서  80  98   95   90
예은  70  95  100   90

In [37]:
df1['국어'] = 80 # 없는  column을 넣어주면 됨

In [38]:
df1

    수학  영어   음악   체육  국어
이름
길동  90  99   85  100  80
준서  80  98   95   90  80
예은  70  95  100   90  80

In [39]:
#열추가
df1['국어'] = 80
print(df1)

    수학  영어   음악   체육  국어
이름
길동  90  99   85  100  80
준서  80  98   95   90  80
예은  70  95  100   90  80

In [40]:
#행추가
#df1.loc[3] = ['동규', 90 ,80,70, 60, 80]
#df1.tail()
df1.loc['동규'] = [90, 80, 70, 60,80]

In [41]:
print(df1)

    수학  영어   음악   체육  국어
이름
길동  90  99   85  100  80
준서  80  98   95   90  80
예은  70  95  100   90  80
동규  90  80   70   60  80

# 2. Pandas2

In [150]:
exam_data = {'이름':['서준', '우현','인아'],  
             '수학':[90,80,70], 
             '영어' : [99,98,95], 
             '음악':[85,95,100], 
             '체육':[100,90,90]}
df1 = pd.DataFrame(exam_data)

In [151]:
df1.set_index('이름', inplace=True) 
df1

    수학  영어   음악   체육
이름
서준  90  99   85  100
우현  80  98   95   90
인아  70  95  100   90

In [152]:
df1.iloc[0][3] = 80

In [153]:
df1

    수학  영어   음악  체육
이름
서준  90  99   85  80
우현  80  98   95  90
인아  70  95  100  90

In [154]:
df1.loc['서준']['체육']   = 100

In [155]:
df1

    수학  영어   음악   체육
이름
서준  90  99   85  100
우현  80  98   95   90
인아  70  95  100   90

In [156]:
df1 #서준의 음악체육을 50점으로
#서준의 음악은 100점 체육은 50점으로 한줄에

    수학  영어   음악   체육
이름
서준  90  99   85  100
우현  80  98   95   90
인아  70  95  100   90

In [157]:
df1.loc['서준', ['음악', '체육']] = 50  
df1

    수학  영어   음악  체육
이름
서준  90  99   50  50
우현  80  98   95  90
인아  70  95  100  90

In [158]:
df1.loc['서준', ['음악', '체육']] = 100, 50  
df1

    수학  영어   음악  체육
이름
서준  90  99  100  50
우현  80  98   95  90
인아  70  95  100  90

Transpose

In [171]:
exam_data = {'이름':['서준', '우현','인아'],  
             '수학':[90,80,70], 
             '영어' : [99,98,95], 
             '음악':[85,95,100], 
             '체육':[100,90,90]}
df = pd.DataFrame(exam_data)

In [167]:
#df = df.transpose() 
#df = df.T

In [172]:
df

   이름  수학  영어   음악   체육
0  서준  90  99   85  100
1  우현  80  98   95   90
2  인아  70  95  100   90

In [162]:
#인덱스 설정

In [173]:
ndf = df.set_index(['이름'])

In [174]:
ndf.set_index('음악')

     수학  영어   체육
음악
85   90  99  100
95   80  98   90
100  70  95   90

In [177]:
ndf2 = ndf.set_index(['음악', '수학'])
ndf2

        영어   체육
음악  수학
85  90  99  100
95  80  98   90
100 70  95   90

In [178]:
dict_data = {'c0' : [1,2,3], 'c1' : [4,5,6], 'c2' : [7,8,9], 'c3' : [10,11,12], 'c4' : [13,14,15]}
df2 = pd.DataFrame(dict_data, index=['r0','r1','r2'])
df2

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [179]:
index_list = ['r0', 'r1','r2', 'r3','r4']
ndf = df2.reindex(index_list)
ndf

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [180]:
ndf2 = df2.reindex(index_list, fill_value=0) #NaN -> 0 으로 값입력
ndf2

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [181]:
ndf2.reset_index() # -> 앞에 0,1,2,3 생김 / 반복 가능함

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15
3    r3   0   0   0   0   0
4    r4   0   0   0   0   0

In [182]:
dict_data = {'c0' : [1,2,3], 'c1' : [4,5,6], 'c2' : [7,8,9], 'c3' : [10,11,12], 'c4' : [13,14,15]}
df3 = pd.DataFrame(dict_data, index=['r0','r1','r2'])
df3

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [183]:
ndf3 = df3.sort_index(ascending=False) #인덱스 내림차순으로 정렬
ndf3

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [184]:
ndf4 = df3.sort_values(by='c1', ascending=True)  #인덱스 올림차순으로 정렬
ndf4

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

Series

In [185]:
student1 = pd.Series({'국어':100, '수학':80, '영어' : 90,})
print(student1)

국어    100
수학     80
영어     90
dtype: int64

In [187]:
percent = student1 / 200
percent

국어    0.50
수학    0.40
영어    0.45
dtype: float64

In [188]:
student1 = pd.Series({'국어':100, '수학':80, '영어' : 90})
student2 = pd.Series({'국어':80, '수학':90, '영어' : 85})

In [189]:
add = student1 + student2
add

국어    180
수학    170
영어    175
dtype: int64

In [191]:
sub = student1 - student2
sub

국어    20
수학   -10
영어     5
dtype: int64

In [192]:
mul = student1 * student2
mul

국어    8000
수학    7200
영어    7650
dtype: int64

In [193]:
div = student1 / student2
div

국어    1.250000
수학    0.888889
영어    1.058824
dtype: float64

In [194]:
import numpy as np

In [195]:
student1 = pd.Series({'국어':np.nan, '수학':80, '영어' : 90})
student2 = pd.Series({'국어':80, '수학':90, '영어' : 85})

In [196]:
add = student1 + student2 #nan +80 -> NaN 으로 반환  사칙 연산 다 그러함 
#평균 등 자료 분석 시 오류 발생할 수 있음 캐바캐로 대체, 제외 등 하여야함
add

국어      NaN
수학    170.0
영어    175.0
dtype: float64

In [197]:
sub = student1 - student2
sub

국어     NaN
수학   -10.0
영어     5.0
dtype: float64

In [198]:
mul = student1 * student2
mul

국어       NaN
수학    7200.0
영어    7650.0
dtype: float64

In [199]:
div = student1 / student2
div

국어         NaN
수학    0.888889
영어    1.058824
dtype: float64

In [204]:
student1 = pd.Series({'국어':np.nan, '수학':80, '영어' : 90})
student2 = pd.Series ({'수학':90, '영어' : 85})

In [205]:
sr_add= student1.add(student2, fill_value=0)
sr_sub= student1.sub(student2, fill_value=0)
sr_add=student1.add(student2, fill_value=0)
sr_add=student1.add(student2, fill_value=0)
sr_add

국어      NaN
수학    170.0
영어    175.0
dtype: float64

In [ ]:
sr_sub = student1 - student2
sr_mul = student1 - student2
sr_div = student1 - student2
sr_sub

In [206]:
import seaborn as sns

In [207]:
titanic = sns.load_dataset('titanic')

In [209]:
#sns.get_dataset_names() #diamonds, mpg -> 차 배기량, iris -> 꽃 자주 씀

In [211]:
df = titanic.loc[:, ['age', 'fare']]

In [215]:
df.head() #상위 5개 만 보여줌

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [ ]:
df.tail() #하위 5개 만 보여줌

In [218]:
df1 =  df + 10

In [219]:
df1.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [221]:
df3 = df1 - df #888 번 대이터 없음
df3.tail()

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0